services:
  postgres:
    image: postgres:16
    container_name: moveo_ha_db
    restart: always
    environment:
      POSTGRES_DB: moveo_ha_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
