spring:
  application:
    name: moveo-ha

  datasource:
    url: jdbc:postgresql://localhost:5432/moveo_ha_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.type.preferred_enum_type: postgres_enum
      hibernate:
        format_sql: true
        show_sql: false

  liquibase:
    change-log: classpath:db/changelog/master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_KgMVvBy3a

security:
  cognito:
    client-id: 6fqs3j1l6ckgpe1g294mfn6b3b

logging:
  level:
    com.moveo.ha.service: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: OFF

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
